# Generated by Django 3.2.9 on 2022-01-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['-published_on'],
            },
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
