# Generated by Django 3.2.9 on 2022-01-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20220121_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
