# Generated by Django 3.2.9 on 2022-02-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20220201_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
