# Generated by Django 3.2.9 on 2022-02-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20220214_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Donation',
        ),
    ]
