# Generated by Django 3.2.9 on 2022-02-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_donation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='time',
        ),
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
