# Generated by Django 3.2.9 on 2022-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20220219_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='donation',
            name='fave_image',
            field=models.ImageField(null=True, upload_to='images/tiles/'),
        ),
    ]
