# Generated by Django 3.2.9 on 2022-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20220219_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fave_img', models.ImageField(upload_to='images/tiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='donation',
            name='fave_image',
        ),
    ]
