# Generated by Django 3.2.9 on 2022-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
