# Generated by Django 3.2.9 on 2022-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fave_image', models.ImageField(upload_to='')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
