# Generated by Django 3.2.9 on 2022-02-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_barbertile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbertile',
            name='fave_image',
            field=models.TextField(),
        ),
    ]
