# Generated by Django 3.2.9 on 2022-02-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_auto_20220223_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('artist', 'content')},
        ),
    ]
