# Generated by Django 3.2.9 on 2022-02-23 22:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('mysite', '0033_auto_20220223_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedTags',
            new_name='LikedTag',
        ),
    ]
