# Generated by Django 3.2.9 on 2022-03-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_post_number_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbertile',
            name='fave_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
